services:
  lyndrix:
    build:
      context: .. # Zeigt ins Root-Verzeichnis deines Repositories
      dockerfile: docker/Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: lyndrix-core
    restart: unless-stopped
    ports:
      - "80:8081"
    volumes:
      - lyndrix_plugins_prod:/app/plugins
      - lyndrix_secure_data:/data/security
    env_file: .env.prod # Lädt die Prod-Werte!
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    container_name: lyndrix-db
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - db_prod_storage:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-uadmin",
          "-p${DB_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:latest
    container_name: lyndrix-vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_prod_storage:/vault/file
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}}'
    command: server

volumes:
  db_prod_storage:
  vault_prod_storage:
  lyndrix_plugins_prod:
  lyndrix_secure_data:
